name: Issue bot

on:
  issues:
    types: [opened, edited]

jobs:
  updateGallery:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'Paste or Upload below. They are meant for BOTS ONLY!!!')
    outputs:
      sanityCheck: ${{ steps.sanity_check.outputs.message }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all to get authors of every template.

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm ci
        working-directory: scripts

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Save issue into a file
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/railmapgen/rmp-gallery/issues/${{ github.event.issue.number }} > $HOME/issue.json
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Sanity check
        id: sanity_check
        run: node --loader ts-node/esm ./sanity-check.ts
        working-directory: scripts
      - name: output ${{ steps.sanity_check.outputs.message }}
        run: echo ${{ steps.sanity_check.outputs.message }}

  updateIssueIfFailed:
    runs-on: ubuntu-latest
    needs: updateGallery
    if: ${{ failure() && needs.updateGallery.outputs.sanityCheck != 'pass' }}
    steps:
      - name: Output ${{ needs.updateGallery.outputs.sanityCheck }}
        run: echo ${{ needs.updateGallery.outputs.sanityCheck }}
        
      - name: Comment if failed
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thank you for your contribution. However, upon review, your work did not pass the sanity check due to the following reason:

            - ${{ needs.updateGallery.outputs.sanityCheck }}
            
            This issue will be closed, and no further actions will be taken. Please revise your work accordingly and resubmit it as a new issue.
      - name: Add labels
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labelsToAdd = ['resources', 'need fixing'];
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labelsToAdd
            });
      - name: Close issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed',
              state_reason: 'not_planned'
            });
